apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestingress
  annotations:
spec:
  rules:
  - http:
      paths:
        - path: /apple
          backend:
            serviceName: guestbook-ui
            servicePort: 80
