apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: guestingress
  annotations:
spec:
  ingressClassName: nginx
  rules:
  - host:
    http:
      paths:
       - path: /myapp
         backend:
           service:
             name: guestbook-ui
             port:
               number: 80
